const data = {
  location: {
    name: "Kanpur",
    region: "Uttar Pradesh",
    country: "India",
    lat: 26.47,
    lon: 80.35,
    tz_id: "Asia/Kolkata",
    localtime_epoch: 1604550215,
    localtime: "2020-11-05 9:53",
  },
  current: {
    last_updated_epoch: 1604544109,
    last_updated: "2020-11-05 08:11",
    temp_c: 23.1,
    temp_f: 73.6,
    is_day: 1,
    condition: {
      text: "Sunny",
      icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
      code: 1000,
    },
    wind_mph: 3.1,
    wind_kph: 5,
    wind_degree: 246,
    wind_dir: "WSW",
    pressure_mb: 1013,
    pressure_in: 30.4,
    precip_mm: 0,
    precip_in: 0,
    humidity: 28,
    cloud: 0,
    feelslike_c: 23.6,
    feelslike_f: 74.5,
    vis_km: 10,
    vis_miles: 6,
    uv: 6,
    gust_mph: 4.3,
    gust_kph: 6.8,
  },
  forecast: {
    forecastday: [
      {
        date: "2020-11-05",
        date_epoch: 1604534400,
        day: {
          maxtemp_c: 33,
          maxtemp_f: 91.4,
          mintemp_c: 22.1,
          mintemp_f: 71.8,
          avgtemp_c: 27.2,
          avgtemp_f: 80.9,
          maxwind_mph: 6.9,
          maxwind_kph: 11.2,
          totalprecip_mm: 0,
          totalprecip_in: 0,
          avgvis_km: 10,
          avgvis_miles: 6,
          avghumidity: 24,
          daily_will_it_rain: 0,
          daily_chance_of_rain: "0",
          daily_will_it_snow: 0,
          daily_chance_of_snow: "0",
          condition: {
            text: "Sunny",
            icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
            code: 1000,
          },
          uv: 6,
        },
        astro: {
          sunrise: "06:20 AM",
          sunset: "05:24 PM",
          moonrise: "08:54 PM",
          moonset: "10:16 AM",
          moon_phase: "Last Quarter",
          moon_illumination: "62",
        },
        hour: [
          {
            time_epoch: 1604514600,
            time: "2020-11-05 00:00",
            temp_c: 24.3,
            temp_f: 75.7,
            is_day: 0,
            condition: {
              text: "Clear",
              icon: "//cdn.weatherapi.com/weather/64x64/night/113.png",
              code: 1000,
            },
            wind_mph: 2.7,
            wind_kph: 4.3,
            wind_degree: 341,
            wind_dir: "NNW",
            pressure_mb: 1011,
            pressure_in: 30.3,
            precip_mm: 0,
            precip_in: 0,
            humidity: 27,
            cloud: 0,
            feelslike_c: 24,
            feelslike_f: 75.2,
            windchill_c: 24.3,
            windchill_f: 75.7,
            heatindex_c: 24,
            heatindex_f: 75.2,
            dewpoint_c: 3.8,
            dewpoint_f: 38.8,
            will_it_rain: 0,
            chance_of_rain: "0",
            will_it_snow: 0,
            chance_of_snow: "0",
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 3.8,
            gust_kph: 6.1,
          },
          {
            time_epoch: 1604518200,
            time: "2020-11-05 01:00",
            temp_c: 23.9,
            temp_f: 75,
            is_day: 0,
            condition: {
              text: "Clear",
              icon: "//cdn.weatherapi.com/weather/64x64/night/113.png",
              code: 1000,
            },
            wind_mph: 1.8,
            wind_kph: 2.9,
            wind_degree: 339,
            wind_dir: "NNW",
            pressure_mb: 1011,
            pressure_in: 30.3,
            precip_mm: 0,
            precip_in: 0,
            humidity: 27,
            cloud: 0,
            feelslike_c: 23.9,
            feelslike_f: 75,
            windchill_c: 23.9,
            windchill_f: 75,
            heatindex_c: 23.9,
            heatindex_f: 75,
            dewpoint_c: 4.1,
            dewpoint_f: 39.4,
            will_it_rain: 0,
            chance_of_rain: "0",
            will_it_snow: 0,
            chance_of_snow: "0",
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 2.7,
            gust_kph: 4.3,
          },
          {
            time_epoch: 1604521800,
            time: "2020-11-05 02:00",
            temp_c: 23.6,
            temp_f: 74.5,
            is_day: 0,
            condition: {
              text: "Clear",
              icon: "//cdn.weatherapi.com/weather/64x64/night/113.png",
              code: 1000,
            },
            wind_mph: 1.1,
            wind_kph: 1.8,
            wind_degree: 337,
            wind_dir: "NNW",
            pressure_mb: 1011,
            pressure_in: 30.3,
            precip_mm: 0,
            precip_in: 0,
            humidity: 28,
            cloud: 0,
            feelslike_c: 23.8,
            feelslike_f: 74.8,
            windchill_c: 23.6,
            windchill_f: 74.5,
            heatindex_c: 23.8,
            heatindex_f: 74.8,
            dewpoint_c: 4.3,
            dewpoint_f: 39.7,
            will_it_rain: 0,
            chance_of_rain: "0",
            will_it_snow: 0,
            chance_of_snow: "0",
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 1.6,
            gust_kph: 2.5,
          },
          {
            time_epoch: 1604525400,
            time: "2020-11-05 03:00",
            temp_c: 23.1,
            temp_f: 73.6,
            is_day: 0,
            condition: {
              text: "Clear",
              icon: "//cdn.weatherapi.com/weather/64x64/night/113.png",
              code: 1000,
            },
            wind_mph: 1.6,
            wind_kph: 2.5,
            wind_degree: 306,
            wind_dir: "NW",
            pressure_mb: 1011,
            pressure_in: 30.3,
            precip_mm: 0,
            precip_in: 0,
            humidity: 29,
            cloud: 0,
            feelslike_c: 23.6,
            feelslike_f: 74.5,
            windchill_c: 23.1,
            windchill_f: 73.6,
            heatindex_c: 23.6,
            heatindex_f: 74.5,
            dewpoint_c: 4,
            dewpoint_f: 39.2,
            will_it_rain: 0,
            chance_of_rain: "0",
            will_it_snow: 0,
            chance_of_snow: "0",
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 2.5,
            gust_kph: 4,
          },
          {
            time_epoch: 1604529000,
            time: "2020-11-05 04:00",
            temp_c: 22.6,
            temp_f: 72.7,
            is_day: 0,
            condition: {
              text: "Clear",
              icon: "//cdn.weatherapi.com/weather/64x64/night/113.png",
              code: 1000,
            },
            wind_mph: 2.2,
            wind_kph: 3.6,
            wind_degree: 275,
            wind_dir: "W",
            pressure_mb: 1012,
            pressure_in: 30.3,
            precip_mm: 0,
            precip_in: 0,
            humidity: 29,
            cloud: 0,
            feelslike_c: 23.4,
            feelslike_f: 74.1,
            windchill_c: 22.6,
            windchill_f: 72.7,
            heatindex_c: 23.4,
            heatindex_f: 74.1,
            dewpoint_c: 3.7,
            dewpoint_f: 38.7,
            will_it_rain: 0,
            chance_of_rain: "0",
            will_it_snow: 0,
            chance_of_snow: "0",
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 3.1,
            gust_kph: 5,
          },
          {
            time_epoch: 1604532600,
            time: "2020-11-05 05:00",
            temp_c: 22.1,
            temp_f: 71.8,
            is_day: 0,
            condition: {
              text: "Clear",
              icon: "//cdn.weatherapi.com/weather/64x64/night/113.png",
              code: 1000,
            },
            wind_mph: 2.7,
            wind_kph: 4.3,
            wind_degree: 245,
            wind_dir: "WSW",
            pressure_mb: 1012,
            pressure_in: 30.3,
            precip_mm: 0,
            precip_in: 0,
            humidity: 29,
            cloud: 0,
            feelslike_c: 23.2,
            feelslike_f: 73.8,
            windchill_c: 22.1,
            windchill_f: 71.8,
            heatindex_c: 23.2,
            heatindex_f: 73.8,
            dewpoint_c: 3.4,
            dewpoint_f: 38.1,
            will_it_rain: 0,
            chance_of_rain: "0",
            will_it_snow: 0,
            chance_of_snow: "0",
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 4,
            gust_kph: 6.5,
          },
          {
            time_epoch: 1604536200,
            time: "2020-11-05 06:00",
            temp_c: 23.1,
            temp_f: 73.6,
            is_day: 1,
            condition: {
              text: "Sunny",
              icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
              code: 1000,
            },
            wind_mph: 3.1,
            wind_kph: 5,
            wind_degree: 246,
            wind_dir: "WSW",
            pressure_mb: 1013,
            pressure_in: 30.4,
            precip_mm: 0,
            precip_in: 0,
            humidity: 28,
            cloud: 0,
            feelslike_c: 23.6,
            feelslike_f: 74.5,
            windchill_c: 23.1,
            windchill_f: 73.6,
            heatindex_c: 23.6,
            heatindex_f: 74.5,
            dewpoint_c: 3.8,
            dewpoint_f: 38.8,
            will_it_rain: 0,
            chance_of_rain: "0",
            will_it_snow: 0,
            chance_of_snow: "0",
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 4.3,
            gust_kph: 6.8,
          },
          {
            time_epoch: 1604539800,
            time: "2020-11-05 07:00",
            temp_c: 24.2,
            temp_f: 75.6,
            is_day: 1,
            condition: {
              text: "Sunny",
              icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
              code: 1000,
            },
            wind_mph: 3.8,
            wind_kph: 6.1,
            wind_degree: 246,
            wind_dir: "WSW",
            pressure_mb: 1014,
            pressure_in: 30.4,
            precip_mm: 0,
            precip_in: 0,
            humidity: 27,
            cloud: 0,
            feelslike_c: 24.1,
            feelslike_f: 75.4,
            windchill_c: 24.2,
            windchill_f: 75.6,
            heatindex_c: 24.1,
            heatindex_f: 75.4,
            dewpoint_c: 4.1,
            dewpoint_f: 39.4,
            will_it_rain: 0,
            chance_of_rain: "0",
            will_it_snow: 0,
            chance_of_snow: "0",
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 4.7,
            gust_kph: 7.6,
          },
          {
            time_epoch: 1604543400,
            time: "2020-11-05 08:00",
            temp_c: 25.2,
            temp_f: 77.4,
            is_day: 1,
            condition: {
              text: "Sunny",
              icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
              code: 1000,
            },
            wind_mph: 4.3,
            wind_kph: 6.8,
            wind_degree: 247,
            wind_dir: "WSW",
            pressure_mb: 1014,
            pressure_in: 30.4,
            precip_mm: 0,
            precip_in: 0,
            humidity: 26,
            cloud: 0,
            feelslike_c: 24.5,
            feelslike_f: 76.1,
            windchill_c: 25.2,
            windchill_f: 77.4,
            heatindex_c: 24.5,
            heatindex_f: 76.1,
            dewpoint_c: 4.5,
            dewpoint_f: 40.1,
            will_it_rain: 0,
            chance_of_rain: "0",
            will_it_snow: 0,
            chance_of_snow: "0",
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 4.9,
            gust_kph: 7.9,
          },
          {
            time_epoch: 1604547000,
            time: "2020-11-05 09:00",
            temp_c: 27,
            temp_f: 80.6,
            is_day: 1,
            condition: {
              text: "Sunny",
              icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
              code: 1000,
            },
            wind_mph: 4.9,
            wind_kph: 7.9,
            wind_degree: 251,
            wind_dir: "WSW",
            pressure_mb: 1014,
            pressure_in: 30.4,
            precip_mm: 0,
            precip_in: 0,
            humidity: 24,
            cloud: 0,
            feelslike_c: 25.8,
            feelslike_f: 78.4,
            windchill_c: 27,
            windchill_f: 80.6,
            heatindex_c: 25.8,
            heatindex_f: 78.4,
            dewpoint_c: 4.4,
            dewpoint_f: 39.9,
            will_it_rain: 0,
            chance_of_rain: "0",
            will_it_snow: 0,
            chance_of_snow: "0",
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 5.6,
            gust_kph: 9,
          },
          {
            time_epoch: 1604550600,
            time: "2020-11-05 10:00",
            temp_c: 28.7,
            temp_f: 83.7,
            is_day: 1,
            condition: {
              text: "Sunny",
              icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
              code: 1000,
            },
            wind_mph: 5.4,
            wind_kph: 8.6,
            wind_degree: 256,
            wind_dir: "WSW",
            pressure_mb: 1014,
            pressure_in: 30.4,
            precip_mm: 0,
            precip_in: 0,
            humidity: 21,
            cloud: 0,
            feelslike_c: 27,
            feelslike_f: 80.6,
            windchill_c: 28.7,
            windchill_f: 83.7,
            heatindex_c: 27,
            heatindex_f: 80.6,
            dewpoint_c: 4.3,
            dewpoint_f: 39.7,
            will_it_rain: 0,
            chance_of_rain: "0",
            will_it_snow: 0,
            chance_of_snow: "0",
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 6.3,
            gust_kph: 10.1,
          },
          {
            time_epoch: 1604554200,
            time: "2020-11-05 11:00",
            temp_c: 30.5,
            temp_f: 86.9,
            is_day: 1,
            condition: {
              text: "Sunny",
              icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
              code: 1000,
            },
            wind_mph: 6,
            wind_kph: 9.7,
            wind_degree: 260,
            wind_dir: "W",
            pressure_mb: 1014,
            pressure_in: 30.4,
            precip_mm: 0,
            precip_in: 0,
            humidity: 19,
            cloud: 0,
            feelslike_c: 28.3,
            feelslike_f: 82.9,
            windchill_c: 30.5,
            windchill_f: 86.9,
            heatindex_c: 28.3,
            heatindex_f: 82.9,
            dewpoint_c: 4.2,
            dewpoint_f: 39.6,
            will_it_rain: 0,
            chance_of_rain: "0",
            will_it_snow: 0,
            chance_of_snow: "0",
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 6.9,
            gust_kph: 11.2,
          },
          {
            time_epoch: 1604557800,
            time: "2020-11-05 12:00",
            temp_c: 31.3,
            temp_f: 88.3,
            is_day: 1,
            condition: {
              text: "Sunny",
              icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
              code: 1000,
            },
            wind_mph: 6.3,
            wind_kph: 10.1,
            wind_degree: 275,
            wind_dir: "W",
            pressure_mb: 1013,
            pressure_in: 30.4,
            precip_mm: 0,
            precip_in: 0,
            humidity: 18,
            cloud: 0,
            feelslike_c: 29.2,
            feelslike_f: 84.6,
            windchill_c: 31.3,
            windchill_f: 88.3,
            heatindex_c: 29.2,
            heatindex_f: 84.6,
            dewpoint_c: 3.8,
            dewpoint_f: 38.8,
            will_it_rain: 0,
            chance_of_rain: "0",
            will_it_snow: 0,
            chance_of_snow: "0",
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 7.4,
            gust_kph: 11.9,
          },
          {
            time_epoch: 1604561400,
            time: "2020-11-05 13:00",
            temp_c: 32.2,
            temp_f: 90,
            is_day: 1,
            condition: {
              text: "Sunny",
              icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
              code: 1000,
            },
            wind_mph: 6.7,
            wind_kph: 10.8,
            wind_degree: 290,
            wind_dir: "WNW",
            pressure_mb: 1013,
            pressure_in: 30.4,
            precip_mm: 0,
            precip_in: 0,
            humidity: 16,
            cloud: 0,
            feelslike_c: 30,
            feelslike_f: 86,
            windchill_c: 32.2,
            windchill_f: 90,
            heatindex_c: 30,
            heatindex_f: 86,
            dewpoint_c: 3.3,
            dewpoint_f: 37.9,
            will_it_rain: 0,
            chance_of_rain: "0",
            will_it_snow: 0,
            chance_of_snow: "0",
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 7.6,
            gust_kph: 12.2,
          },
          {
            time_epoch: 1604565000,
            time: "2020-11-05 14:00",
            temp_c: 33,
            temp_f: 91.4,
            is_day: 1,
            condition: {
              text: "Sunny",
              icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
              code: 1000,
            },
            wind_mph: 6.9,
            wind_kph: 11.2,
            wind_degree: 305,
            wind_dir: "NW",
            pressure_mb: 1012,
            pressure_in: 30.3,
            precip_mm: 0,
            precip_in: 0,
            humidity: 15,
            cloud: 0,
            feelslike_c: 30.9,
            feelslike_f: 87.6,
            windchill_c: 33,
            windchill_f: 91.4,
            heatindex_c: 30.9,
            heatindex_f: 87.6,
            dewpoint_c: 2.9,
            dewpoint_f: 37.2,
            will_it_rain: 0,
            chance_of_rain: "0",
            will_it_snow: 0,
            chance_of_snow: "0",
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 8.1,
            gust_kph: 13,
          },
          {
            time_epoch: 1604568600,
            time: "2020-11-05 15:00",
            temp_c: 31.9,
            temp_f: 89.4,
            is_day: 1,
            condition: {
              text: "Sunny",
              icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
              code: 1000,
            },
            wind_mph: 5.6,
            wind_kph: 9,
            wind_degree: 309,
            wind_dir: "NW",
            pressure_mb: 1012,
            pressure_in: 30.3,
            precip_mm: 0,
            precip_in: 0,
            humidity: 17,
            cloud: 0,
            feelslike_c: 29.9,
            feelslike_f: 85.8,
            windchill_c: 31.9,
            windchill_f: 89.4,
            heatindex_c: 29.9,
            heatindex_f: 85.8,
            dewpoint_c: 3.8,
            dewpoint_f: 38.8,
            will_it_rain: 0,
            chance_of_rain: "0",
            will_it_snow: 0,
            chance_of_snow: "0",
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 6.7,
            gust_kph: 10.8,
          },
          {
            time_epoch: 1604572200,
            time: "2020-11-05 16:00",
            temp_c: 30.9,
            temp_f: 87.6,
            is_day: 1,
            condition: {
              text: "Sunny",
              icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
              code: 1000,
            },
            wind_mph: 4.3,
            wind_kph: 6.8,
            wind_degree: 312,
            wind_dir: "NW",
            pressure_mb: 1012,
            pressure_in: 30.3,
            precip_mm: 0,
            precip_in: 0,
            humidity: 19,
            cloud: 0,
            feelslike_c: 28.8,
            feelslike_f: 83.8,
            windchill_c: 30.9,
            windchill_f: 87.6,
            heatindex_c: 28.8,
            heatindex_f: 83.8,
            dewpoint_c: 4.6,
            dewpoint_f: 40.3,
            will_it_rain: 0,
            chance_of_rain: "0",
            will_it_snow: 0,
            chance_of_snow: "0",
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 5.1,
            gust_kph: 8.3,
          },
          {
            time_epoch: 1604575800,
            time: "2020-11-05 17:00",
            temp_c: 29.8,
            temp_f: 85.6,
            is_day: 0,
            condition: {
              text: "Clear",
              icon: "//cdn.weatherapi.com/weather/64x64/night/113.png",
              code: 1000,
            },
            wind_mph: 2.9,
            wind_kph: 4.7,
            wind_degree: 316,
            wind_dir: "NW",
            pressure_mb: 1012,
            pressure_in: 30.3,
            precip_mm: 0,
            precip_in: 0,
            humidity: 22,
            cloud: 0,
            feelslike_c: 27.8,
            feelslike_f: 82,
            windchill_c: 29.8,
            windchill_f: 85.6,
            heatindex_c: 27.8,
            heatindex_f: 82,
            dewpoint_c: 5.5,
            dewpoint_f: 41.9,
            will_it_rain: 0,
            chance_of_rain: "0",
            will_it_snow: 0,
            chance_of_snow: "0",
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 3.8,
            gust_kph: 6.1,
          },
          {
            time_epoch: 1604579400,
            time: "2020-11-05 18:00",
            temp_c: 29.1,
            temp_f: 84.4,
            is_day: 0,
            condition: {
              text: "Clear",
              icon: "//cdn.weatherapi.com/weather/64x64/night/113.png",
              code: 1000,
            },
            wind_mph: 2.9,
            wind_kph: 4.7,
            wind_degree: 320,
            wind_dir: "NW",
            pressure_mb: 1012,
            pressure_in: 30.4,
            precip_mm: 0,
            precip_in: 0,
            humidity: 22,
            cloud: 0,
            feelslike_c: 27.2,
            feelslike_f: 81,
            windchill_c: 29.1,
            windchill_f: 84.4,
            heatindex_c: 27.2,
            heatindex_f: 81,
            dewpoint_c: 5.4,
            dewpoint_f: 41.7,
            will_it_rain: 0,
            chance_of_rain: "0",
            will_it_snow: 0,
            chance_of_snow: "0",
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 3.8,
            gust_kph: 6.1,
          },
          {
            time_epoch: 1604583000,
            time: "2020-11-05 19:00",
            temp_c: 28.3,
            temp_f: 82.9,
            is_day: 0,
            condition: {
              text: "Clear",
              icon: "//cdn.weatherapi.com/weather/64x64/night/113.png",
              code: 1000,
            },
            wind_mph: 2.7,
            wind_kph: 4.3,
            wind_degree: 324,
            wind_dir: "NW",
            pressure_mb: 1013,
            pressure_in: 30.4,
            precip_mm: 0,
            precip_in: 0,
            humidity: 23,
            cloud: 0,
            feelslike_c: 26.7,
            feelslike_f: 80.1,
            windchill_c: 28.3,
            windchill_f: 82.9,
            heatindex_c: 26.7,
            heatindex_f: 80.1,
            dewpoint_c: 5.3,
            dewpoint_f: 41.5,
            will_it_rain: 0,
            chance_of_rain: "0",
            will_it_snow: 0,
            chance_of_snow: "0",
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 3.6,
            gust_kph: 5.8,
          },
          {
            time_epoch: 1604586600,
            time: "2020-11-05 20:00",
            temp_c: 27.6,
            temp_f: 81.7,
            is_day: 0,
            condition: {
              text: "Clear",
              icon: "//cdn.weatherapi.com/weather/64x64/night/113.png",
              code: 1000,
            },
            wind_mph: 2.7,
            wind_kph: 4.3,
            wind_degree: 327,
            wind_dir: "NNW",
            pressure_mb: 1014,
            pressure_in: 30.4,
            precip_mm: 0,
            precip_in: 0,
            humidity: 24,
            cloud: 0,
            feelslike_c: 26.1,
            feelslike_f: 79,
            windchill_c: 27.6,
            windchill_f: 81.7,
            heatindex_c: 26.1,
            heatindex_f: 79,
            dewpoint_c: 5.2,
            dewpoint_f: 41.4,
            will_it_rain: 0,
            chance_of_rain: "0",
            will_it_snow: 0,
            chance_of_snow: "0",
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 3.6,
            gust_kph: 5.8,
          },
          {
            time_epoch: 1604590200,
            time: "2020-11-05 21:00",
            temp_c: 26.9,
            temp_f: 80.4,
            is_day: 0,
            condition: {
              text: "Clear",
              icon: "//cdn.weatherapi.com/weather/64x64/night/113.png",
              code: 1000,
            },
            wind_mph: 2.2,
            wind_kph: 3.6,
            wind_degree: 327,
            wind_dir: "NNW",
            pressure_mb: 1014,
            pressure_in: 30.4,
            precip_mm: 0,
            precip_in: 0,
            humidity: 25,
            cloud: 0,
            feelslike_c: 25.6,
            feelslike_f: 78.1,
            windchill_c: 26.9,
            windchill_f: 80.4,
            heatindex_c: 25.6,
            heatindex_f: 78.1,
            dewpoint_c: 5,
            dewpoint_f: 41,
            will_it_rain: 0,
            chance_of_rain: "0",
            will_it_snow: 0,
            chance_of_snow: "0",
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 2.9,
            gust_kph: 4.7,
          },
          {
            time_epoch: 1604593800,
            time: "2020-11-05 22:00",
            temp_c: 26.1,
            temp_f: 79,
            is_day: 0,
            condition: {
              text: "Clear",
              icon: "//cdn.weatherapi.com/weather/64x64/night/113.png",
              code: 1000,
            },
            wind_mph: 1.6,
            wind_kph: 2.5,
            wind_degree: 326,
            wind_dir: "NNW",
            pressure_mb: 1014,
            pressure_in: 30.4,
            precip_mm: 0,
            precip_in: 0,
            humidity: 25,
            cloud: 0,
            feelslike_c: 25.1,
            feelslike_f: 77.2,
            windchill_c: 26.1,
            windchill_f: 79,
            heatindex_c: 25.1,
            heatindex_f: 77.2,
            dewpoint_c: 4.9,
            dewpoint_f: 40.8,
            will_it_rain: 0,
            chance_of_rain: "0",
            will_it_snow: 0,
            chance_of_snow: "0",
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 2.5,
            gust_kph: 4,
          },
          {
            time_epoch: 1604597400,
            time: "2020-11-05 23:00",
            temp_c: 25.4,
            temp_f: 77.7,
            is_day: 0,
            condition: {
              text: "Clear",
              icon: "//cdn.weatherapi.com/weather/64x64/night/113.png",
              code: 1000,
            },
            wind_mph: 1.1,
            wind_kph: 1.8,
            wind_degree: 326,
            wind_dir: "NNW",
            pressure_mb: 1014,
            pressure_in: 30.4,
            precip_mm: 0,
            precip_in: 0,
            humidity: 26,
            cloud: 0,
            feelslike_c: 24.6,
            feelslike_f: 76.3,
            windchill_c: 25.4,
            windchill_f: 77.7,
            heatindex_c: 24.6,
            heatindex_f: 76.3,
            dewpoint_c: 4.7,
            dewpoint_f: 40.5,
            will_it_rain: 0,
            chance_of_rain: "0",
            will_it_snow: 0,
            chance_of_snow: "0",
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 1.8,
            gust_kph: 2.9,
          },
        ],
      },
      {
        date: "2020-11-06",
        date_epoch: 1604620800,
        day: {
          maxtemp_c: 34,
          maxtemp_f: 93.2,
          mintemp_c: 21.8,
          mintemp_f: 71.2,
          avgtemp_c: 27.6,
          avgtemp_f: 81.7,
          maxwind_mph: 7.4,
          maxwind_kph: 11.9,
          totalprecip_mm: 0,
          totalprecip_in: 0,
          avgvis_km: 10,
          avgvis_miles: 6,
          avghumidity: 22,
          daily_will_it_rain: 0,
          daily_chance_of_rain: "0",
          daily_will_it_snow: 0,
          daily_chance_of_snow: "0",
          condition: {
            text: "Sunny",
            icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
            code: 1000,
          },
          uv: 6,
        },
        astro: {
          sunrise: "06:21 AM",
          sunset: "05:23 PM",
          moonrise: "09:49 PM",
          moonset: "11:09 AM",
          moon_phase: "Last Quarter",
          moon_illumination: "55",
        },
        hour: [
          {
            time_epoch: 1604601000,
            time: "2020-11-06 00:00",
            temp_c: 25.1,
            temp_f: 77.2,
            is_day: 0,
            condition: {
              text: "Clear",
              icon: "//cdn.weatherapi.com/weather/64x64/night/113.png",
              code: 1000,
            },
            wind_mph: 1.6,
            wind_kph: 2.5,
            wind_degree: 304,
            wind_dir: "NW",
            pressure_mb: 1014,
            pressure_in: 30.4,
            precip_mm: 0,
            precip_in: 0,
            humidity: 27,
            cloud: 0,
            feelslike_c: 24.4,
            feelslike_f: 75.9,
            windchill_c: 25.1,
            windchill_f: 77.2,
            heatindex_c: 24.4,
            heatindex_f: 75.9,
            dewpoint_c: 4.6,
            dewpoint_f: 40.3,
            will_it_rain: 0,
            chance_of_rain: "0",
            will_it_snow: 0,
            chance_of_snow: "0",
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 2.5,
            gust_kph: 4,
          },
          {
            time_epoch: 1604604600,
            time: "2020-11-06 01:00",
            temp_c: 24.7,
            temp_f: 76.5,
            is_day: 0,
            condition: {
              text: "Clear",
              icon: "//cdn.weatherapi.com/weather/64x64/night/113.png",
              code: 1000,
            },
            wind_mph: 2,
            wind_kph: 3.2,
            wind_degree: 282,
            wind_dir: "WNW",
            pressure_mb: 1013,
            pressure_in: 30.4,
            precip_mm: 0,
            precip_in: 0,
            humidity: 27,
            cloud: 0,
            feelslike_c: 24.3,
            feelslike_f: 75.7,
            windchill_c: 24.7,
            windchill_f: 76.5,
            heatindex_c: 24.3,
            heatindex_f: 75.7,
            dewpoint_c: 4.6,
            dewpoint_f: 40.3,
            will_it_rain: 0,
            chance_of_rain: "0",
            will_it_snow: 0,
            chance_of_snow: "0",
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 2.9,
            gust_kph: 4.7,
          },
          {
            time_epoch: 1604608200,
            time: "2020-11-06 02:00",
            temp_c: 24.4,
            temp_f: 75.9,
            is_day: 0,
            condition: {
              text: "Clear",
              icon: "//cdn.weatherapi.com/weather/64x64/night/113.png",
              code: 1000,
            },
            wind_mph: 2.5,
            wind_kph: 4,
            wind_degree: 260,
            wind_dir: "W",
            pressure_mb: 1013,
            pressure_in: 30.4,
            precip_mm: 0,
            precip_in: 0,
            humidity: 28,
            cloud: 0,
            feelslike_c: 24.1,
            feelslike_f: 75.4,
            windchill_c: 24.4,
            windchill_f: 75.9,
            heatindex_c: 24.1,
            heatindex_f: 75.4,
            dewpoint_c: 4.5,
            dewpoint_f: 40.1,
            will_it_rain: 0,
            chance_of_rain: "0",
            will_it_snow: 0,
            chance_of_snow: "0",
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 3.6,
            gust_kph: 5.8,
          },
          {
            time_epoch: 1604611800,
            time: "2020-11-06 03:00",
            temp_c: 23.5,
            temp_f: 74.3,
            is_day: 0,
            condition: {
              text: "Clear",
              icon: "//cdn.weatherapi.com/weather/64x64/night/113.png",
              code: 1000,
            },
            wind_mph: 3.1,
            wind_kph: 5,
            wind_degree: 258,
            wind_dir: "WSW",
            pressure_mb: 1013,
            pressure_in: 30.4,
            precip_mm: 0,
            precip_in: 0,
            humidity: 28,
            cloud: 0,
            feelslike_c: 23.8,
            feelslike_f: 74.8,
            windchill_c: 23.5,
            windchill_f: 74.3,
            heatindex_c: 23.8,
            heatindex_f: 74.8,
            dewpoint_c: 4,
            dewpoint_f: 39.2,
            will_it_rain: 0,
            chance_of_rain: "0",
            will_it_snow: 0,
            chance_of_snow: "0",
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 4.9,
            gust_kph: 7.9,
          },
          {
            time_epoch: 1604615400,
            time: "2020-11-06 04:00",
            temp_c: 22.7,
            temp_f: 72.9,
            is_day: 0,
            condition: {
              text: "Clear",
              icon: "//cdn.weatherapi.com/weather/64x64/night/113.png",
              code: 1000,
            },
            wind_mph: 3.8,
            wind_kph: 6.1,
            wind_degree: 255,
            wind_dir: "WSW",
            pressure_mb: 1014,
            pressure_in: 30.4,
            precip_mm: 0,
            precip_in: 0,
            humidity: 29,
            cloud: 0,
            feelslike_c: 23.4,
            feelslike_f: 74.1,
            windchill_c: 22.7,
            windchill_f: 72.9,
            heatindex_c: 23.4,
            heatindex_f: 74.1,
            dewpoint_c: 3.6,
            dewpoint_f: 38.5,
            will_it_rain: 0,
            chance_of_rain: "0",
            will_it_snow: 0,
            chance_of_snow: "0",
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 6,
            gust_kph: 9.7,
          },
          {
            time_epoch: 1604619000,
            time: "2020-11-06 05:00",
            temp_c: 21.8,
            temp_f: 71.2,
            is_day: 0,
            condition: {
              text: "Clear",
              icon: "//cdn.weatherapi.com/weather/64x64/night/113.png",
              code: 1000,
            },
            wind_mph: 4.5,
            wind_kph: 7.2,
            wind_degree: 253,
            wind_dir: "WSW",
            pressure_mb: 1014,
            pressure_in: 30.4,
            precip_mm: 0,
            precip_in: 0,
            humidity: 29,
            cloud: 0,
            feelslike_c: 21.8,
            feelslike_f: 71.2,
            windchill_c: 21.8,
            windchill_f: 71.2,
            heatindex_c: 23.1,
            heatindex_f: 73.6,
            dewpoint_c: 3.1,
            dewpoint_f: 37.6,
            will_it_rain: 0,
            chance_of_rain: "0",
            will_it_snow: 0,
            chance_of_snow: "0",
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 7.4,
            gust_kph: 11.9,
          },
          {
            time_epoch: 1604622600,
            time: "2020-11-06 06:00",
            temp_c: 23.1,
            temp_f: 73.6,
            is_day: 1,
            condition: {
              text: "Sunny",
              icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
              code: 1000,
            },
            wind_mph: 4.5,
            wind_kph: 7.2,
            wind_degree: 257,
            wind_dir: "WSW",
            pressure_mb: 1015,
            pressure_in: 30.4,
            precip_mm: 0,
            precip_in: 0,
            humidity: 28,
            cloud: 0,
            feelslike_c: 23.7,
            feelslike_f: 74.7,
            windchill_c: 23.1,
            windchill_f: 73.6,
            heatindex_c: 23.7,
            heatindex_f: 74.7,
            dewpoint_c: 3.8,
            dewpoint_f: 38.8,
            will_it_rain: 0,
            chance_of_rain: "0",
            will_it_snow: 0,
            chance_of_snow: "0",
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 6.5,
            gust_kph: 10.4,
          },
          {
            time_epoch: 1604626200,
            time: "2020-11-06 07:00",
            temp_c: 24.5,
            temp_f: 76.1,
            is_day: 1,
            condition: {
              text: "Sunny",
              icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
              code: 1000,
            },
            wind_mph: 4.3,
            wind_kph: 6.8,
            wind_degree: 261,
            wind_dir: "W",
            pressure_mb: 1016,
            pressure_in: 30.5,
            precip_mm: 0,
            precip_in: 0,
            humidity: 27,
            cloud: 0,
            feelslike_c: 24.3,
            feelslike_f: 75.7,
            windchill_c: 24.5,
            windchill_f: 76.1,
            heatindex_c: 24.3,
            heatindex_f: 75.7,
            dewpoint_c: 4.4,
            dewpoint_f: 39.9,
            will_it_rain: 0,
            chance_of_rain: "0",
            will_it_snow: 0,
            chance_of_snow: "0",
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 5.8,
            gust_kph: 9.4,
          },
          {
            time_epoch: 1604629800,
            time: "2020-11-06 08:00",
            temp_c: 25.8,
            temp_f: 78.4,
            is_day: 1,
            condition: {
              text: "Sunny",
              icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
              code: 1000,
            },
            wind_mph: 4.3,
            wind_kph: 6.8,
            wind_degree: 266,
            wind_dir: "W",
            pressure_mb: 1017,
            pressure_in: 30.5,
            precip_mm: 0,
            precip_in: 0,
            humidity: 26,
            cloud: 0,
            feelslike_c: 24.9,
            feelslike_f: 76.8,
            windchill_c: 25.8,
            windchill_f: 78.4,
            heatindex_c: 24.9,
            heatindex_f: 76.8,
            dewpoint_c: 5.1,
            dewpoint_f: 41.2,
            will_it_rain: 0,
            chance_of_rain: "0",
            will_it_snow: 0,
            chance_of_snow: "0",
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 4.9,
            gust_kph: 7.9,
          },
          {
            time_epoch: 1604633400,
            time: "2020-11-06 09:00",
            temp_c: 27.7,
            temp_f: 81.9,
            is_day: 1,
            condition: {
              text: "Sunny",
              icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
              code: 1000,
            },
            wind_mph: 4.7,
            wind_kph: 7.6,
            wind_degree: 272,
            wind_dir: "W",
            pressure_mb: 1017,
            pressure_in: 30.5,
            precip_mm: 0,
            precip_in: 0,
            humidity: 23,
            cloud: 0,
            feelslike_c: 26.4,
            feelslike_f: 79.5,
            windchill_c: 27.7,
            windchill_f: 81.9,
            heatindex_c: 26.4,
            heatindex_f: 79.5,
            dewpoint_c: 4.6,
            dewpoint_f: 40.3,
            will_it_rain: 0,
            chance_of_rain: "0",
            will_it_snow: 0,
            chance_of_snow: "0",
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 5.4,
            gust_kph: 8.6,
          },
          {
            time_epoch: 1604637000,
            time: "2020-11-06 10:00",
            temp_c: 29.7,
            temp_f: 85.5,
            is_day: 1,
            condition: {
              text: "Sunny",
              icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
              code: 1000,
            },
            wind_mph: 5.1,
            wind_kph: 8.3,
            wind_degree: 278,
            wind_dir: "W",
            pressure_mb: 1016,
            pressure_in: 30.5,
            precip_mm: 0,
            precip_in: 0,
            humidity: 20,
            cloud: 0,
            feelslike_c: 27.9,
            feelslike_f: 82.2,
            windchill_c: 29.7,
            windchill_f: 85.5,
            heatindex_c: 27.9,
            heatindex_f: 82.2,
            dewpoint_c: 4.2,
            dewpoint_f: 39.6,
            will_it_rain: 0,
            chance_of_rain: "0",
            will_it_snow: 0,
            chance_of_snow: "0",
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 6,
            gust_kph: 9.7,
          },
          {
            time_epoch: 1604640600,
            time: "2020-11-06 11:00",
            temp_c: 31.6,
            temp_f: 88.9,
            is_day: 1,
            condition: {
              text: "Sunny",
              icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
              code: 1000,
            },
            wind_mph: 5.6,
            wind_kph: 9,
            wind_degree: 284,
            wind_dir: "WNW",
            pressure_mb: 1016,
            pressure_in: 30.5,
            precip_mm: 0,
            precip_in: 0,
            humidity: 17,
            cloud: 0,
            feelslike_c: 29.4,
            feelslike_f: 84.9,
            windchill_c: 31.6,
            windchill_f: 88.9,
            heatindex_c: 29.4,
            heatindex_f: 84.9,
            dewpoint_c: 3.7,
            dewpoint_f: 38.7,
            will_it_rain: 0,
            chance_of_rain: "0",
            will_it_snow: 0,
            chance_of_snow: "0",
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 6.5,
            gust_kph: 10.4,
          },
          {
            time_epoch: 1604644200,
            time: "2020-11-06 12:00",
            temp_c: 32.4,
            temp_f: 90.3,
            is_day: 1,
            condition: {
              text: "Sunny",
              icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
              code: 1000,
            },
            wind_mph: 6.3,
            wind_kph: 10.1,
            wind_degree: 296,
            wind_dir: "WNW",
            pressure_mb: 1015,
            pressure_in: 30.5,
            precip_mm: 0,
            precip_in: 0,
            humidity: 16,
            cloud: 0,
            feelslike_c: 30.3,
            feelslike_f: 86.5,
            windchill_c: 32.4,
            windchill_f: 90.3,
            heatindex_c: 30.3,
            heatindex_f: 86.5,
            dewpoint_c: 2.8,
            dewpoint_f: 37,
            will_it_rain: 0,
            chance_of_rain: "0",
            will_it_snow: 0,
            chance_of_snow: "0",
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 7.2,
            gust_kph: 11.5,
          },
          {
            time_epoch: 1604647800,
            time: "2020-11-06 13:00",
            temp_c: 33.2,
            temp_f: 91.8,
            is_day: 1,
            condition: {
              text: "Sunny",
              icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
              code: 1000,
            },
            wind_mph: 6.7,
            wind_kph: 10.8,
            wind_degree: 308,
            wind_dir: "NW",
            pressure_mb: 1015,
            pressure_in: 30.4,
            precip_mm: 0,
            precip_in: 0,
            humidity: 14,
            cloud: 0,
            feelslike_c: 31.1,
            feelslike_f: 88,
            windchill_c: 33.2,
            windchill_f: 91.8,
            heatindex_c: 31.1,
            heatindex_f: 88,
            dewpoint_c: 2,
            dewpoint_f: 35.6,
            will_it_rain: 0,
            chance_of_rain: "0",
            will_it_snow: 0,
            chance_of_snow: "0",
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 7.8,
            gust_kph: 12.6,
          },
          {
            time_epoch: 1604651400,
            time: "2020-11-06 14:00",
            temp_c: 34,
            temp_f: 93.2,
            is_day: 1,
            condition: {
              text: "Sunny",
              icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
              code: 1000,
            },
            wind_mph: 7.4,
            wind_kph: 11.9,
            wind_degree: 320,
            wind_dir: "NW",
            pressure_mb: 1014,
            pressure_in: 30.4,
            precip_mm: 0,
            precip_in: 0,
            humidity: 12,
            cloud: 0,
            feelslike_c: 32,
            feelslike_f: 89.6,
            windchill_c: 34,
            windchill_f: 93.2,
            heatindex_c: 32,
            heatindex_f: 89.6,
            dewpoint_c: 1.1,
            dewpoint_f: 34,
            will_it_rain: 0,
            chance_of_rain: "0",
            will_it_snow: 0,
            chance_of_snow: "0",
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 8.5,
            gust_kph: 13.7,
          },
          {
            time_epoch: 1604655000,
            time: "2020-11-06 15:00",
            temp_c: 32.7,
            temp_f: 90.9,
            is_day: 1,
            condition: {
              text: "Sunny",
              icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
              code: 1000,
            },
            wind_mph: 6,
            wind_kph: 9.7,
            wind_degree: 328,
            wind_dir: "NNW",
            pressure_mb: 1014,
            pressure_in: 30.4,
            precip_mm: 0,
            precip_in: 0,
            humidity: 14,
            cloud: 0,
            feelslike_c: 30.7,
            feelslike_f: 87.3,
            windchill_c: 32.7,
            windchill_f: 90.9,
            heatindex_c: 30.7,
            heatindex_f: 87.3,
            dewpoint_c: 1.9,
            dewpoint_f: 35.4,
            will_it_rain: 0,
            chance_of_rain: "0",
            will_it_snow: 0,
            chance_of_snow: "0",
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 7.4,
            gust_kph: 11.9,
          },
          {
            time_epoch: 1604658600,
            time: "2020-11-06 16:00",
            temp_c: 31.5,
            temp_f: 88.7,
            is_day: 1,
            condition: {
              text: "Sunny",
              icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
              code: 1000,
            },
            wind_mph: 4.9,
            wind_kph: 7.9,
            wind_degree: 335,
            wind_dir: "NNW",
            pressure_mb: 1014,
            pressure_in: 30.4,
            precip_mm: 0,
            precip_in: 0,
            humidity: 16,
            cloud: 0,
            feelslike_c: 29.3,
            feelslike_f: 84.7,
            windchill_c: 31.5,
            windchill_f: 88.7,
            heatindex_c: 29.3,
            heatindex_f: 84.7,
            dewpoint_c: 2.8,
            dewpoint_f: 37,
            will_it_rain: 0,
            chance_of_rain: "0",
            will_it_snow: 0,
            chance_of_snow: "0",
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 6.3,
            gust_kph: 10.1,
          },
          {
            time_epoch: 1604662200,
            time: "2020-11-06 17:00",
            temp_c: 30.2,
            temp_f: 86.4,
            is_day: 0,
            condition: {
              text: "Clear",
              icon: "//cdn.weatherapi.com/weather/64x64/night/113.png",
              code: 1000,
            },
            wind_mph: 3.6,
            wind_kph: 5.8,
            wind_degree: 342,
            wind_dir: "NNW",
            pressure_mb: 1013,
            pressure_in: 30.4,
            precip_mm: 0,
            precip_in: 0,
            humidity: 18,
            cloud: 0,
            feelslike_c: 28,
            feelslike_f: 82.4,
            windchill_c: 30.2,
            windchill_f: 86.4,
            heatindex_c: 28,
            heatindex_f: 82.4,
            dewpoint_c: 3.6,
            dewpoint_f: 38.5,
            will_it_rain: 0,
            chance_of_rain: "0",
            will_it_snow: 0,
            chance_of_snow: "0",
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 5.1,
            gust_kph: 8.3,
          },
          {
            time_epoch: 1604665800,
            time: "2020-11-06 18:00",
            temp_c: 29.4,
            temp_f: 84.9,
            is_day: 0,
            condition: {
              text: "Clear",
              icon: "//cdn.weatherapi.com/weather/64x64/night/113.png",
              code: 1000,
            },
            wind_mph: 3.4,
            wind_kph: 5.4,
            wind_degree: 237,
            wind_dir: "WSW",
            pressure_mb: 1014,
            pressure_in: 30.4,
            precip_mm: 0,
            precip_in: 0,
            humidity: 19,
            cloud: 0,
            feelslike_c: 27.3,
            feelslike_f: 81.1,
            windchill_c: 29.4,
            windchill_f: 84.9,
            heatindex_c: 27.3,
            heatindex_f: 81.1,
            dewpoint_c: 3.6,
            dewpoint_f: 38.5,
            will_it_rain: 0,
            chance_of_rain: "0",
            will_it_snow: 0,
            chance_of_snow: "0",
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 4.7,
            gust_kph: 7.6,
          },
          {
            time_epoch: 1604669400,
            time: "2020-11-06 19:00",
            temp_c: 28.5,
            temp_f: 83.3,
            is_day: 0,
            condition: {
              text: "Clear",
              icon: "//cdn.weatherapi.com/weather/64x64/night/113.png",
              code: 1000,
            },
            wind_mph: 2.9,
            wind_kph: 4.7,
            wind_degree: 132,
            wind_dir: "SE",
            pressure_mb: 1015,
            pressure_in: 30.4,
            precip_mm: 0,
            precip_in: 0,
            humidity: 20,
            cloud: 0,
            feelslike_c: 26.6,
            feelslike_f: 79.9,
            windchill_c: 28.5,
            windchill_f: 83.3,
            heatindex_c: 26.6,
            heatindex_f: 79.9,
            dewpoint_c: 3.5,
            dewpoint_f: 38.3,
            will_it_rain: 0,
            chance_of_rain: "0",
            will_it_snow: 0,
            chance_of_snow: "0",
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 4.3,
            gust_kph: 6.8,
          },
          {
            time_epoch: 1604673000,
            time: "2020-11-06 20:00",
            temp_c: 27.7,
            temp_f: 81.9,
            is_day: 0,
            condition: {
              text: "Clear",
              icon: "//cdn.weatherapi.com/weather/64x64/night/113.png",
              code: 1000,
            },
            wind_mph: 2.7,
            wind_kph: 4.3,
            wind_degree: 26,
            wind_dir: "NNE",
            pressure_mb: 1015,
            pressure_in: 30.5,
            precip_mm: 0,
            precip_in: 0,
            humidity: 21,
            cloud: 0,
            feelslike_c: 25.9,
            feelslike_f: 78.6,
            windchill_c: 27.7,
            windchill_f: 81.9,
            heatindex_c: 25.9,
            heatindex_f: 78.6,
            dewpoint_c: 3.5,
            dewpoint_f: 38.3,
            will_it_rain: 0,
            chance_of_rain: "0",
            will_it_snow: 0,
            chance_of_snow: "0",
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 3.8,
            gust_kph: 6.1,
          },
          {
            time_epoch: 1604676600,
            time: "2020-11-06 21:00",
            temp_c: 26.9,
            temp_f: 80.4,
            is_day: 0,
            condition: {
              text: "Clear",
              icon: "//cdn.weatherapi.com/weather/64x64/night/113.png",
              code: 1000,
            },
            wind_mph: 2.5,
            wind_kph: 4,
            wind_degree: 36,
            wind_dir: "NE",
            pressure_mb: 1015,
            pressure_in: 30.5,
            precip_mm: 0,
            precip_in: 0,
            humidity: 22,
            cloud: 0,
            feelslike_c: 25.4,
            feelslike_f: 77.7,
            windchill_c: 26.9,
            windchill_f: 80.4,
            heatindex_c: 25.4,
            heatindex_f: 77.7,
            dewpoint_c: 3.5,
            dewpoint_f: 38.3,
            will_it_rain: 0,
            chance_of_rain: "0",
            will_it_snow: 0,
            chance_of_snow: "0",
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 3.6,
            gust_kph: 5.8,
          },
          {
            time_epoch: 1604680200,
            time: "2020-11-06 22:00",
            temp_c: 26.2,
            temp_f: 79.2,
            is_day: 0,
            condition: {
              text: "Clear",
              icon: "//cdn.weatherapi.com/weather/64x64/night/113.png",
              code: 1000,
            },
            wind_mph: 2.2,
            wind_kph: 3.6,
            wind_degree: 47,
            wind_dir: "NE",
            pressure_mb: 1015,
            pressure_in: 30.5,
            precip_mm: 0,
            precip_in: 0,
            humidity: 23,
            cloud: 0,
            feelslike_c: 25,
            feelslike_f: 77,
            windchill_c: 26.2,
            windchill_f: 79.2,
            heatindex_c: 25,
            heatindex_f: 77,
            dewpoint_c: 3.6,
            dewpoint_f: 38.5,
            will_it_rain: 0,
            chance_of_rain: "0",
            will_it_snow: 0,
            chance_of_snow: "0",
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 3.4,
            gust_kph: 5.4,
          },
          {
            time_epoch: 1604683800,
            time: "2020-11-06 23:00",
            temp_c: 25.4,
            temp_f: 77.7,
            is_day: 0,
            condition: {
              text: "Clear",
              icon: "//cdn.weatherapi.com/weather/64x64/night/113.png",
              code: 1000,
            },
            wind_mph: 2,
            wind_kph: 3.2,
            wind_degree: 57,
            wind_dir: "ENE",
            pressure_mb: 1015,
            pressure_in: 30.5,
            precip_mm: 0,
            precip_in: 0,
            humidity: 24,
            cloud: 0,
            feelslike_c: 24.5,
            feelslike_f: 76.1,
            windchill_c: 25.4,
            windchill_f: 77.7,
            heatindex_c: 24.5,
            heatindex_f: 76.1,
            dewpoint_c: 3.6,
            dewpoint_f: 38.5,
            will_it_rain: 0,
            chance_of_rain: "0",
            will_it_snow: 0,
            chance_of_snow: "0",
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 3.1,
            gust_kph: 5,
          },
        ],
      },
      {
        date: "2020-11-07",
        date_epoch: 1604707200,
        day: {
          maxtemp_c: 34.4,
          maxtemp_f: 93.9,
          mintemp_c: 22.3,
          mintemp_f: 72.1,
          avgtemp_c: 27.7,
          avgtemp_f: 81.8,
          maxwind_mph: 6.5,
          maxwind_kph: 10.4,
          totalprecip_mm: 0,
          totalprecip_in: 0,
          avgvis_km: 10,
          avgvis_miles: 6,
          avghumidity: 21,
          daily_will_it_rain: 0,
          daily_chance_of_rain: "0",
          daily_will_it_snow: 0,
          daily_chance_of_snow: "0",
          condition: {
            text: "Sunny",
            icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
            code: 1000,
          },
          uv: 6,
        },
        astro: {
          sunrise: "06:21 AM",
          sunset: "05:22 PM",
          moonrise: "10:47 PM",
          moonset: "12:00 PM",
          moon_phase: "Waning Crescent",
          moon_illumination: "48",
        },
        hour: [
          {
            time_epoch: 1604687400,
            time: "2020-11-07 00:00",
            temp_c: 25.1,
            temp_f: 77.2,
            is_day: 0,
            condition: {
              text: "Clear",
              icon: "//cdn.weatherapi.com/weather/64x64/night/113.png",
              code: 1000,
            },
            wind_mph: 2,
            wind_kph: 3.2,
            wind_degree: 99,
            wind_dir: "E",
            pressure_mb: 1015,
            pressure_in: 30.5,
            precip_mm: 0,
            precip_in: 0,
            humidity: 25,
            cloud: 0,
            feelslike_c: 24.4,
            feelslike_f: 75.9,
            windchill_c: 25.1,
            windchill_f: 77.2,
            heatindex_c: 24.4,
            heatindex_f: 75.9,
            dewpoint_c: 3.7,
            dewpoint_f: 38.7,
            will_it_rain: 0,
            chance_of_rain: "0",
            will_it_snow: 0,
            chance_of_snow: "0",
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 3.1,
            gust_kph: 5,
          },
          {
            time_epoch: 1604691000,
            time: "2020-11-07 01:00",
            temp_c: 24.9,
            temp_f: 76.8,
            is_day: 0,
            condition: {
              text: "Clear",
              icon: "//cdn.weatherapi.com/weather/64x64/night/113.png",
              code: 1000,
            },
            wind_mph: 2.2,
            wind_kph: 3.6,
            wind_degree: 141,
            wind_dir: "SE",
            pressure_mb: 1015,
            pressure_in: 30.4,
            precip_mm: 0,
            precip_in: 0,
            humidity: 26,
            cloud: 0,
            feelslike_c: 24.2,
            feelslike_f: 75.6,
            windchill_c: 24.9,
            windchill_f: 76.8,
            heatindex_c: 24.2,
            heatindex_f: 75.6,
            dewpoint_c: 3.9,
            dewpoint_f: 39,
            will_it_rain: 0,
            chance_of_rain: "0",
            will_it_snow: 0,
            chance_of_snow: "0",
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 3.1,
            gust_kph: 5,
          },
          {
            time_epoch: 1604694600,
            time: "2020-11-07 02:00",
            temp_c: 24.6,
            temp_f: 76.3,
            is_day: 0,
            condition: {
              text: "Clear",
              icon: "//cdn.weatherapi.com/weather/64x64/night/113.png",
              code: 1000,
            },
            wind_mph: 2.2,
            wind_kph: 3.6,
            wind_degree: 184,
            wind_dir: "S",
            pressure_mb: 1015,
            pressure_in: 30.4,
            precip_mm: 0,
            precip_in: 0,
            humidity: 26,
            cloud: 0,
            feelslike_c: 24.1,
            feelslike_f: 75.4,
            windchill_c: 24.6,
            windchill_f: 76.3,
            heatindex_c: 24.1,
            heatindex_f: 75.4,
            dewpoint_c: 4,
            dewpoint_f: 39.2,
            will_it_rain: 0,
            chance_of_rain: "0",
            will_it_snow: 0,
            chance_of_snow: "0",
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 3.1,
            gust_kph: 5,
          },
          {
            time_epoch: 1604698200,
            time: "2020-11-07 03:00",
            temp_c: 23.8,
            temp_f: 74.8,
            is_day: 0,
            condition: {
              text: "Clear",
              icon: "//cdn.weatherapi.com/weather/64x64/night/113.png",
              code: 1000,
            },
            wind_mph: 2.9,
            wind_kph: 4.7,
            wind_degree: 198,
            wind_dir: "SSW",
            pressure_mb: 1015,
            pressure_in: 30.4,
            precip_mm: 0,
            precip_in: 0,
            humidity: 26,
            cloud: 0,
            feelslike_c: 23.7,
            feelslike_f: 74.7,
            windchill_c: 23.8,
            windchill_f: 74.8,
            heatindex_c: 23.7,
            heatindex_f: 74.7,
            dewpoint_c: 3.4,
            dewpoint_f: 38.1,
            will_it_rain: 0,
            chance_of_rain: "0",
            will_it_snow: 0,
            chance_of_snow: "0",
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 4.5,
            gust_kph: 7.2,
          },
          {
            time_epoch: 1604701800,
            time: "2020-11-07 04:00",
            temp_c: 23.1,
            temp_f: 73.6,
            is_day: 0,
            condition: {
              text: "Clear",
              icon: "//cdn.weatherapi.com/weather/64x64/night/113.png",
              code: 1000,
            },
            wind_mph: 3.4,
            wind_kph: 5.4,
            wind_degree: 211,
            wind_dir: "SSW",
            pressure_mb: 1015,
            pressure_in: 30.5,
            precip_mm: 0,
            precip_in: 0,
            humidity: 27,
            cloud: 0,
            feelslike_c: 23.4,
            feelslike_f: 74.1,
            windchill_c: 23.1,
            windchill_f: 73.6,
            heatindex_c: 23.4,
            heatindex_f: 74.1,
            dewpoint_c: 2.9,
            dewpoint_f: 37.2,
            will_it_rain: 0,
            chance_of_rain: "0",
            will_it_snow: 0,
            chance_of_snow: "0",
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 5.6,
            gust_kph: 9,
          },
          {
            time_epoch: 1604705400,
            time: "2020-11-07 05:00",
            temp_c: 22.3,
            temp_f: 72.1,
            is_day: 0,
            condition: {
              text: "Clear",
              icon: "//cdn.weatherapi.com/weather/64x64/night/113.png",
              code: 1000,
            },
            wind_mph: 4,
            wind_kph: 6.5,
            wind_degree: 225,
            wind_dir: "SW",
            pressure_mb: 1015,
            pressure_in: 30.5,
            precip_mm: 0,
            precip_in: 0,
            humidity: 27,
            cloud: 0,
            feelslike_c: 23,
            feelslike_f: 73.4,
            windchill_c: 22.3,
            windchill_f: 72.1,
            heatindex_c: 23,
            heatindex_f: 73.4,
            dewpoint_c: 2.3,
            dewpoint_f: 36.1,
            will_it_rain: 0,
            chance_of_rain: "0",
            will_it_snow: 0,
            chance_of_snow: "0",
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 6.9,
            gust_kph: 11.2,
          },
          {
            time_epoch: 1604709000,
            time: "2020-11-07 06:00",
            temp_c: 23.4,
            temp_f: 74.1,
            is_day: 1,
            condition: {
              text: "Sunny",
              icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
              code: 1000,
            },
            wind_mph: 4.3,
            wind_kph: 6.8,
            wind_degree: 240,
            wind_dir: "WSW",
            pressure_mb: 1016,
            pressure_in: 30.5,
            precip_mm: 0,
            precip_in: 0,
            humidity: 26,
            cloud: 0,
            feelslike_c: 23.5,
            feelslike_f: 74.3,
            windchill_c: 23.4,
            windchill_f: 74.1,
            heatindex_c: 23.5,
            heatindex_f: 74.3,
            dewpoint_c: 2.8,
            dewpoint_f: 37,
            will_it_rain: 0,
            chance_of_rain: "0",
            will_it_snow: 0,
            chance_of_snow: "0",
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 6.5,
            gust_kph: 10.4,
          },
          {
            time_epoch: 1604712600,
            time: "2020-11-07 07:00",
            temp_c: 24.4,
            temp_f: 75.9,
            is_day: 1,
            condition: {
              text: "Sunny",
              icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
              code: 1000,
            },
            wind_mph: 4.5,
            wind_kph: 7.2,
            wind_degree: 255,
            wind_dir: "WSW",
            pressure_mb: 1017,
            pressure_in: 30.5,
            precip_mm: 0,
            precip_in: 0,
            humidity: 25,
            cloud: 0,
            feelslike_c: 24.1,
            feelslike_f: 75.4,
            windchill_c: 24.4,
            windchill_f: 75.9,
            heatindex_c: 24.1,
            heatindex_f: 75.4,
            dewpoint_c: 3.4,
            dewpoint_f: 38.1,
            will_it_rain: 0,
            chance_of_rain: "0",
            will_it_snow: 0,
            chance_of_snow: "0",
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 5.8,
            gust_kph: 9.4,
          },
          {
            time_epoch: 1604716200,
            time: "2020-11-07 08:00",
            temp_c: 25.5,
            temp_f: 77.9,
            is_day: 1,
            condition: {
              text: "Sunny",
              icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
              code: 1000,
            },
            wind_mph: 4.7,
            wind_kph: 7.6,
            wind_degree: 270,
            wind_dir: "W",
            pressure_mb: 1018,
            pressure_in: 30.5,
            precip_mm: 0,
            precip_in: 0,
            humidity: 25,
            cloud: 0,
            feelslike_c: 24.6,
            feelslike_f: 76.3,
            windchill_c: 25.5,
            windchill_f: 77.9,
            heatindex_c: 24.6,
            heatindex_f: 76.3,
            dewpoint_c: 3.9,
            dewpoint_f: 39,
            will_it_rain: 0,
            chance_of_rain: "0",
            will_it_snow: 0,
            chance_of_snow: "0",
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 5.4,
            gust_kph: 8.6,
          },
          {
            time_epoch: 1604719800,
            time: "2020-11-07 09:00",
            temp_c: 27.5,
            temp_f: 81.5,
            is_day: 1,
            condition: {
              text: "Sunny",
              icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
              code: 1000,
            },
            wind_mph: 4.9,
            wind_kph: 7.9,
            wind_degree: 275,
            wind_dir: "W",
            pressure_mb: 1017,
            pressure_in: 30.5,
            precip_mm: 0,
            precip_in: 0,
            humidity: 22,
            cloud: 0,
            feelslike_c: 26.2,
            feelslike_f: 79.2,
            windchill_c: 27.5,
            windchill_f: 81.5,
            heatindex_c: 26.2,
            heatindex_f: 79.2,
            dewpoint_c: 3.4,
            dewpoint_f: 38.1,
            will_it_rain: 0,
            chance_of_rain: "0",
            will_it_snow: 0,
            chance_of_snow: "0",
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 5.8,
            gust_kph: 9.4,
          },
          {
            time_epoch: 1604723400,
            time: "2020-11-07 10:00",
            temp_c: 29.5,
            temp_f: 85.1,
            is_day: 1,
            condition: {
              text: "Sunny",
              icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
              code: 1000,
            },
            wind_mph: 5.4,
            wind_kph: 8.6,
            wind_degree: 280,
            wind_dir: "W",
            pressure_mb: 1017,
            pressure_in: 30.5,
            precip_mm: 0,
            precip_in: 0,
            humidity: 19,
            cloud: 0,
            feelslike_c: 27.7,
            feelslike_f: 81.9,
            windchill_c: 29.5,
            windchill_f: 85.1,
            heatindex_c: 27.7,
            heatindex_f: 81.9,
            dewpoint_c: 3,
            dewpoint_f: 37.4,
            will_it_rain: 0,
            chance_of_rain: "0",
            will_it_snow: 0,
            chance_of_snow: "0",
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 6,
            gust_kph: 9.7,
          },
          {
            time_epoch: 1604727000,
            time: "2020-11-07 11:00",
            temp_c: 31.5,
            temp_f: 88.7,
            is_day: 1,
            condition: {
              text: "Sunny",
              icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
              code: 1000,
            },
            wind_mph: 5.6,
            wind_kph: 9,
            wind_degree: 286,
            wind_dir: "WNW",
            pressure_mb: 1017,
            pressure_in: 30.5,
            precip_mm: 0,
            precip_in: 0,
            humidity: 16,
            cloud: 0,
            feelslike_c: 29.3,
            feelslike_f: 84.7,
            windchill_c: 31.5,
            windchill_f: 88.7,
            heatindex_c: 29.3,
            heatindex_f: 84.7,
            dewpoint_c: 2.5,
            dewpoint_f: 36.5,
            will_it_rain: 0,
            chance_of_rain: "0",
            will_it_snow: 0,
            chance_of_snow: "0",
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 6.5,
            gust_kph: 10.4,
          },
          {
            time_epoch: 1604730600,
            time: "2020-11-07 12:00",
            temp_c: 32.5,
            temp_f: 90.5,
            is_day: 1,
            condition: {
              text: "Sunny",
              icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
              code: 1000,
            },
            wind_mph: 5.8,
            wind_kph: 9.4,
            wind_degree: 293,
            wind_dir: "WNW",
            pressure_mb: 1016,
            pressure_in: 30.5,
            precip_mm: 0,
            precip_in: 0,
            humidity: 15,
            cloud: 0,
            feelslike_c: 30.4,
            feelslike_f: 86.7,
            windchill_c: 32.5,
            windchill_f: 90.5,
            heatindex_c: 30.4,
            heatindex_f: 86.7,
            dewpoint_c: 1.9,
            dewpoint_f: 35.4,
            will_it_rain: 0,
            chance_of_rain: "0",
            will_it_snow: 0,
            chance_of_snow: "0",
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 6.7,
            gust_kph: 10.8,
          },
          {
            time_epoch: 1604734200,
            time: "2020-11-07 13:00",
            temp_c: 33.4,
            temp_f: 92.1,
            is_day: 1,
            condition: {
              text: "Sunny",
              icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
              code: 1000,
            },
            wind_mph: 6.3,
            wind_kph: 10.1,
            wind_degree: 300,
            wind_dir: "WNW",
            pressure_mb: 1015,
            pressure_in: 30.5,
            precip_mm: 0,
            precip_in: 0,
            humidity: 13,
            cloud: 0,
            feelslike_c: 31.4,
            feelslike_f: 88.5,
            windchill_c: 33.4,
            windchill_f: 92.1,
            heatindex_c: 31.4,
            heatindex_f: 88.5,
            dewpoint_c: 1.4,
            dewpoint_f: 34.5,
            will_it_rain: 0,
            chance_of_rain: "0",
            will_it_snow: 0,
            chance_of_snow: "0",
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 7.2,
            gust_kph: 11.5,
          },
          {
            time_epoch: 1604737800,
            time: "2020-11-07 14:00",
            temp_c: 34.4,
            temp_f: 93.9,
            is_day: 1,
            condition: {
              text: "Sunny",
              icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
              code: 1000,
            },
            wind_mph: 6.5,
            wind_kph: 10.4,
            wind_degree: 307,
            wind_dir: "NW",
            pressure_mb: 1014,
            pressure_in: 30.4,
            precip_mm: 0,
            precip_in: 0,
            humidity: 12,
            cloud: 0,
            feelslike_c: 32.5,
            feelslike_f: 90.5,
            windchill_c: 34.4,
            windchill_f: 93.9,
            heatindex_c: 32.5,
            heatindex_f: 90.5,
            dewpoint_c: 0.8,
            dewpoint_f: 33.4,
            will_it_rain: 0,
            chance_of_rain: "0",
            will_it_snow: 0,
            chance_of_snow: "0",
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 7.4,
            gust_kph: 11.9,
          },
          {
            time_epoch: 1604741400,
            time: "2020-11-07 15:00",
            temp_c: 33.1,
            temp_f: 91.6,
            is_day: 1,
            condition: {
              text: "Sunny",
              icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
              code: 1000,
            },
            wind_mph: 5.4,
            wind_kph: 8.6,
            wind_degree: 308,
            wind_dir: "NW",
            pressure_mb: 1014,
            pressure_in: 30.4,
            precip_mm: 0,
            precip_in: 0,
            humidity: 14,
            cloud: 0,
            feelslike_c: 31.1,
            feelslike_f: 88,
            windchill_c: 33.1,
            windchill_f: 91.6,
            heatindex_c: 31.1,
            heatindex_f: 88,
            dewpoint_c: 1.7,
            dewpoint_f: 35.1,
            will_it_rain: 0,
            chance_of_rain: "0",
            will_it_snow: 0,
            chance_of_snow: "0",
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 6.3,
            gust_kph: 10.1,
          },
          {
            time_epoch: 1604745000,
            time: "2020-11-07 16:00",
            temp_c: 31.8,
            temp_f: 89.2,
            is_day: 1,
            condition: {
              text: "Sunny",
              icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
              code: 1000,
            },
            wind_mph: 4,
            wind_kph: 6.5,
            wind_degree: 309,
            wind_dir: "NW",
            pressure_mb: 1014,
            pressure_in: 30.4,
            precip_mm: 0,
            precip_in: 0,
            humidity: 16,
            cloud: 0,
            feelslike_c: 29.7,
            feelslike_f: 85.5,
            windchill_c: 31.8,
            windchill_f: 89.2,
            heatindex_c: 29.7,
            heatindex_f: 85.5,
            dewpoint_c: 2.6,
            dewpoint_f: 36.7,
            will_it_rain: 0,
            chance_of_rain: "0",
            will_it_snow: 0,
            chance_of_snow: "0",
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 5.1,
            gust_kph: 8.3,
          },
          {
            time_epoch: 1604748600,
            time: "2020-11-07 17:00",
            temp_c: 30.5,
            temp_f: 86.9,
            is_day: 0,
            condition: {
              text: "Clear",
              icon: "//cdn.weatherapi.com/weather/64x64/night/113.png",
              code: 1000,
            },
            wind_mph: 2.9,
            wind_kph: 4.7,
            wind_degree: 311,
            wind_dir: "NW",
            pressure_mb: 1014,
            pressure_in: 30.4,
            precip_mm: 0,
            precip_in: 0,
            humidity: 18,
            cloud: 0,
            feelslike_c: 28.3,
            feelslike_f: 82.9,
            windchill_c: 30.5,
            windchill_f: 86.9,
            heatindex_c: 28.3,
            heatindex_f: 82.9,
            dewpoint_c: 3.5,
            dewpoint_f: 38.3,
            will_it_rain: 0,
            chance_of_rain: "0",
            will_it_snow: 0,
            chance_of_snow: "0",
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 4,
            gust_kph: 6.5,
          },
          {
            time_epoch: 1604752200,
            time: "2020-11-07 18:00",
            temp_c: 29.6,
            temp_f: 85.3,
            is_day: 0,
            condition: {
              text: "Clear",
              icon: "//cdn.weatherapi.com/weather/64x64/night/113.png",
              code: 1000,
            },
            wind_mph: 2.9,
            wind_kph: 4.7,
            wind_degree: 208,
            wind_dir: "SSW",
            pressure_mb: 1014,
            pressure_in: 30.4,
            precip_mm: 0,
            precip_in: 0,
            humidity: 19,
            cloud: 0,
            feelslike_c: 27.5,
            feelslike_f: 81.5,
            windchill_c: 29.6,
            windchill_f: 85.3,
            heatindex_c: 27.5,
            heatindex_f: 81.5,
            dewpoint_c: 3.4,
            dewpoint_f: 38.1,
            will_it_rain: 0,
            chance_of_rain: "0",
            will_it_snow: 0,
            chance_of_snow: "0",
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 4,
            gust_kph: 6.5,
          },
          {
            time_epoch: 1604755800,
            time: "2020-11-07 19:00",
            temp_c: 28.6,
            temp_f: 83.5,
            is_day: 0,
            condition: {
              text: "Clear",
              icon: "//cdn.weatherapi.com/weather/64x64/night/113.png",
              code: 1000,
            },
            wind_mph: 2.9,
            wind_kph: 4.7,
            wind_degree: 105,
            wind_dir: "ESE",
            pressure_mb: 1015,
            pressure_in: 30.4,
            precip_mm: 0,
            precip_in: 0,
            humidity: 20,
            cloud: 0,
            feelslike_c: 26.6,
            feelslike_f: 79.9,
            windchill_c: 28.6,
            windchill_f: 83.5,
            heatindex_c: 26.6,
            heatindex_f: 79.9,
            dewpoint_c: 3.2,
            dewpoint_f: 37.8,
            will_it_rain: 0,
            chance_of_rain: "0",
            will_it_snow: 0,
            chance_of_snow: "0",
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 4,
            gust_kph: 6.5,
          },
          {
            time_epoch: 1604759400,
            time: "2020-11-07 20:00",
            temp_c: 27.7,
            temp_f: 81.9,
            is_day: 0,
            condition: {
              text: "Clear",
              icon: "//cdn.weatherapi.com/weather/64x64/night/113.png",
              code: 1000,
            },
            wind_mph: 2.9,
            wind_kph: 4.7,
            wind_degree: 2,
            wind_dir: "N",
            pressure_mb: 1015,
            pressure_in: 30.5,
            precip_mm: 0,
            precip_in: 0,
            humidity: 21,
            cloud: 0,
            feelslike_c: 25.8,
            feelslike_f: 78.4,
            windchill_c: 27.7,
            windchill_f: 81.9,
            heatindex_c: 25.8,
            heatindex_f: 78.4,
            dewpoint_c: 3.1,
            dewpoint_f: 37.6,
            will_it_rain: 0,
            chance_of_rain: "0",
            will_it_snow: 0,
            chance_of_snow: "0",
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 4,
            gust_kph: 6.5,
          },
          {
            time_epoch: 1604763000,
            time: "2020-11-07 21:00",
            temp_c: 26.8,
            temp_f: 80.2,
            is_day: 0,
            condition: {
              text: "Clear",
              icon: "//cdn.weatherapi.com/weather/64x64/night/113.png",
              code: 1000,
            },
            wind_mph: 2.9,
            wind_kph: 4.7,
            wind_degree: 18,
            wind_dir: "NNE",
            pressure_mb: 1015,
            pressure_in: 30.5,
            precip_mm: 0,
            precip_in: 0,
            humidity: 22,
            cloud: 0,
            feelslike_c: 25.3,
            feelslike_f: 77.5,
            windchill_c: 26.8,
            windchill_f: 80.2,
            heatindex_c: 25.3,
            heatindex_f: 77.5,
            dewpoint_c: 3.1,
            dewpoint_f: 37.6,
            will_it_rain: 0,
            chance_of_rain: "0",
            will_it_snow: 0,
            chance_of_snow: "0",
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 4.3,
            gust_kph: 6.8,
          },
          {
            time_epoch: 1604766600,
            time: "2020-11-07 22:00",
            temp_c: 25.9,
            temp_f: 78.6,
            is_day: 0,
            condition: {
              text: "Clear",
              icon: "//cdn.weatherapi.com/weather/64x64/night/113.png",
              code: 1000,
            },
            wind_mph: 3.1,
            wind_kph: 5,
            wind_degree: 33,
            wind_dir: "NNE",
            pressure_mb: 1015,
            pressure_in: 30.5,
            precip_mm: 0,
            precip_in: 0,
            humidity: 23,
            cloud: 0,
            feelslike_c: 24.7,
            feelslike_f: 76.5,
            windchill_c: 25.9,
            windchill_f: 78.6,
            heatindex_c: 24.7,
            heatindex_f: 76.5,
            dewpoint_c: 3.1,
            dewpoint_f: 37.6,
            will_it_rain: 0,
            chance_of_rain: "0",
            will_it_snow: 0,
            chance_of_snow: "0",
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 4.7,
            gust_kph: 7.6,
          },
          {
            time_epoch: 1604770200,
            time: "2020-11-07 23:00",
            temp_c: 25,
            temp_f: 77,
            is_day: 0,
            condition: {
              text: "Clear",
              icon: "//cdn.weatherapi.com/weather/64x64/night/113.png",
              code: 1000,
            },
            wind_mph: 3.1,
            wind_kph: 5,
            wind_degree: 48,
            wind_dir: "NE",
            pressure_mb: 1015,
            pressure_in: 30.5,
            precip_mm: 0,
            precip_in: 0,
            humidity: 24,
            cloud: 0,
            feelslike_c: 24.2,
            feelslike_f: 75.6,
            windchill_c: 25,
            windchill_f: 77,
            heatindex_c: 24.2,
            heatindex_f: 75.6,
            dewpoint_c: 3.1,
            dewpoint_f: 37.6,
            will_it_rain: 0,
            chance_of_rain: "0",
            will_it_snow: 0,
            chance_of_snow: "0",
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 4.9,
            gust_kph: 7.9,
          },
        ],
      },
    ],
  },
  alert: {},
};

export default data;
